- src/components/Join.js
- src/styles/GlobalStyle.js
- src/styles/fonts.css
- src/styles/guide.css
- src/styles/variable.css
221228 style 수정사항.
- Join.js: 주석 제거.
- GlobalStyle.js: guide.css 확정 내용 옮김.
- fonts.css: 사용하지 않는 폰트 삭제.
- guide.css: 임시 전체 주석처리
- variable.css: 사용하지 않는 폰트 삭제.
- 끝.
> feat: styles edit-yeojin

- src/components/Login-yejin.js
Feat: "로그인 기능 구현"
로그인 버튼 onClick 함수 구현(성공-마이페이지로 넘어가기 / 실패-알림창 띄우기)
> feat: 로그인 기능 구현-yejin

- src/App.js
- src/components/Join.js
- src/styles/variable.css
Feat: 회원가입 스타일 컴포넌트 요소 제작
회원가입 form 요소 제작.
- JoinForm
- JoinIp
- JoinLabel
- JoinBtn
> feat: 회원가입 스타일 컴포넌트 요소 제작

- src/App.js
- src/components/Join.js
- src/styles/GlobalStyle.js
- src/styles/variable.css
feat: Join form styled component
- App.js: 불필요한 Guide.js import 삭제.
- Join.js: 스타일드 컴포넌트 추가.
- GlobalStyle.js: 전체 사이즈 클래스명 추가(.wrap).
- variable.css: 갭 사이즈 조정.
> feat: Join form styled component

- src/components/Header.js
- src/components/Help.js
- src/components/index.js
feat: Header.js Help.js 추가
· Help 컴포넌트 모달창 구현
> feat: Header.js Help.js 추가

- package-lock.json
- package.json
- src/App.js
- src/components/Index.js
- src/components/Login.js
Feat: "react-router-dom 구현"
App.js, Index.js에 react-router-dom 관련 내용 추가, Login.js의 데이터를 App.js에서 관리하는 상태로 변경
> feat: react-router-dom 구현

- src/components/Join.js
feat: click and show popup
- click event add
> feat: click and show popup

- src/components/index.js
- src/components/index2.js
> feat: 에러 픽스

- src/App.js
- src/components/Login.js
- src/components/Mypage.js
Feat: Login css 수정, Mypage 테스트
Login css 추가, Mypage props 테스트, App.js에 state, props 추가
> feat: Login css 수정, Mypage 테스트

- src/App.js
- src/components/Footer.js
1. Footer 컴포넌트 생성
- 카피라이트 문구 추가
2. App.js에 Footer 컴포넌트 추가
- 일단 <Fragment> 태그 바깥에 위치 -> Footer 컴포넌트 위치 논의 필요
> Feat: Footer 컴포넌트 생성 및 App.js에 Footer 컴포넌트 추가

- src/App.js
- src/components/Header.js
- src/components/Help.js
- src/components/Index.js
feat: Index.js 수정 및 Help.js 수정
- Main 컴포넌트 제작,  Container 컴포넌트 정렬 수정
- ModalButton 위치 수정
> feat: Index.js 수정 및 Help.js 수정

- src/components/Login.js
> feat:login styled edit-영임

- src/components/Footer.js
- src/components/Header.js
- src/components/Help.js
- src/components/Index.js
<Index.js>
- 버튼 컴포넌트 hover 효과
<Help.js>
- 모달 CSS 수정: 모달 배경화면과 확인 버튼 누르면 닫히게 수정
<Header.js>
- Logo 이미지 상태 관리할 수 있도록 추가
<Footer.js>
- 가운데 정렬
> Feat: Index.js, Help.js, Header.js, Footer.js CSS 수정

- src/components/Login.js
Feat: new clone test
pull 오류로 인해 새로 git clone 하고 잘 되는지 테스트 했습니다.(주석 추가)
> feat: new clone test

- src/App.js
- src/components/Login.js
- src/components/Mypage.js
Feat: Mypage 버튼 구현
Mypage에서 편지를 띄울 수 있는 버튼의 초기 형태 구현
> feat: Mypage 버튼 구현

- src/components/Letter.js
feat: Letter.js 제작
-Letter.js Modal 생성
> feat: Letter.js 제작

- package-lock.json
- package.json
- src/components/Mypage.js
Feat: Mypage 편지없을 때, 모달 추가
Mypage 편지 없을 때 오류 안 나고 문구 뜨게 수정, 모달 추가(다른 팀이 해주셨습니다)
> feat: Mypage 편지없을 때, 모달 추가

- src/App.js
- src/components/Join.js
- src/components/Write.js
feat: App.js Join.js Write.js 수정
- App.js Write추가
- Join.js 체크박스 오류 수정
- Write.js 레이아웃 작업 진행중
> feat: App.js Join.js Write.js 수정

- src/App.js
- src/components/Write.js
feat: Write.js 편지 수정 모달
fix: App.js conflict 해결
> feat: Write.js 편지 수정 모달

- src/App.js
- src/components/Index.js
- src/components/Index2.js
feat: 공유 링크 아이디
-App.js 공유 링크 생성
> feat: 공유 링크 아이디

- src/components/Index2.js
feat: Index2.js 수정
-idCheck state로 유효성 검사 구현
> feat: Index2.js 수정

- src/components/Letter.js
- src/components/Mypage.js
- src/styles/variable.css
Feat: 선택한 버튼만 색깔 바뀌는 기능 구현
선택한 버튼만 색깔 바뀌는 기능 구현, 땅 색깔 variable에 설정, dummydaya Letter에 props로 전달
> feat: 선택한 버튼만 색깔 바뀌는 기능 구현

- src/components/Write.js
feat: 인덱스2에서 sharedId 받기
- Index2.js에서 공유한 사람 ID 받아 노출시키기.
> feat: 인덱스2에서 sharedId 받기

- src/components/Write.js
feat: write.js 모달 구현
- 모달 레이아웃 , css 구현
-
> feat: write.js 모달 구현

- src/components/Join.js
- src/styles/style.js
style: style.js 추가, Join.js 컴포넌트명 변경
- style.js 추가: 공통컴포넌트 추가함
- style.js에 따라 Join.js 컴포넌트명 변경
> style: style.js 추가, Join.js 컴포넌트명 변경

- src/components/Join.js
- src/components/Write.js
fix: Join.js 컴포넌트 불러오기 수정, Write.js 데이터 불러오기 오류 해결
- Join.js : style.js에서 컴포넌트 import로 수정.
- Write.js : textarea, nickname 내용 받아오기 오류 해결.
> fix: Join.js 컴포넌트 불러오기 수정, Write.js 데이터 불러오기 오류 해결

- src/App.js
- src/components/Footer.js
- src/components/Header.js
- src/components/Help.js
- src/components/Index.js
- src/components/Join.js
- src/components/Letter.js
- src/components/Login.js
- src/components/Mypage.js
- src/styles/GlobalStyle.js
- src/styles/style.js
- src/styles/variable.css
style: 전체 페이지 공용으로 사용할 컴포넌트 변경
- 전체 페이지 className='app-wrap' 적용
- 컴포넌트 최상단 페이지 className='wrap' 적용
- 공통 스타일 컴포넌트 style.js 로 통합, 각 페이지에 import 사용
> style: 전체 페이지 공용으로 사용할 컴포넌트 변경

- src/components/Footer.js
- src/components/Help.js
- src/components/Join.js
- src/styles/style.js
- src/styles/variable.css
style: 모달, 푸터 공통 스타일 변경
- 모달 스타일 공통 사용으로 변경 -> style.js 추가
- footer media query 스타일 추가
> style: 모달, 푸터 공통 스타일 변경

- src/components/Help.js
fix: 클릭 오류 수정
- Help.js 클릭 오류 수정
> fix: 클릭 오류 수정

- src/components/Header.js
- src/components/Help.js
feat: header display edit
- header display edit
> feat: header display edit

- src/App.js
- src/components/Write.js
feat: localstorage 구현
-App.js 처음 접속 시 localStorage에 state 값 저장 구현
-Write.js 보내기 버튼 클릭 시 변경 내용 state에 저장 구현
> feat: localstorage 구현

- src/App.js
- src/components/Login.js
- src/components/Mypage.js
feat: Login.js, Mypage.js 수정
-Login.js, Mypage.js 로그인 유지 기능 추가
> feat: Login.js, Mypage.js 수정

- src/components/Write.js
- src/styles/style.js
feat: 편지쓰기 후 수정 기능 추가
- Write.js 수정하기 클릭 기능 추가
> feat: 편지쓰기 후 수정 기능 추가

- src/App.js
fix: userInfo 오류수정
- userInfo 초기화시 빈 배열 할당
> fix: userInfo 오류수정

- src/components/Mypage.js
feat: 버튼 당근 이미지로 변경, 황금당근
Mypage 편지 버튼을 당근 모양 이미지로 변경, 가장 긴 편지는 황금 당근으로 변경
> feat: 버튼 당근 이미지로 변경, 황금당근

- src/App.js
- src/components/Header.js
- src/components/Index2.js
- src/components/Letter.js
feat: Header.js Letter.js 수정
-Header.js 닉네임 추가 기능, Logo 클릭 시 Index.js로 이동, Title 반응형 구현
-Letter.js 보내는 사람 이름 및 편지 내용 받아오기 구현
> feat: Header.js Letter.js 수정

- src/components/Join.js
- src/components/Write.js
> feat: 회원가입, 편지 쓰기 구현 중

- src/components/Write.js
1. 편지 보내기 기능 구현 완료
- (편지) 더미 데이터 업데이트
- 편지 쓰기 완료 후 인덱스로 이동
> feat: Write.js 편지 보내기 기능 구현 완료

- src/App.js
- src/components/Join.js
- src/components/Mypage.js
1. Mypage.js
- userdata 에서 필터링 해오고 map 하기 전 데이터 유효 검사 추가해야함
2. Join.js
- 신규 유저 contentLst 초기화 한 채로 추가
3. App.js
- 한글 아이디 공유 위한 디코딩 코드 추가
> feat: Mypage.js map 전 데이터 조건, Join.js 회원 정보 초기화 값 추가, App.js URI 디코딩 추가

- src/components/Mypage.js
- src/styles/GlobalStyle.js
style: background change
- GlobalStyle.js : background change solid color to gradient
- Mypage.js : base background eliminate
> style: background change

- package-lock.json
- src/App.js
- src/components/Header.js
- src/components/Join.js
- src/components/Write.js
1. package.json conflict 해결
-> font-awesome 설치 과정이 달랐거나 충돌 부분 생긴 것으로 추측
-> 해결 완료된 것처럼 보이나 다른 분들도 문제 없는지 확인해봐야 합니다.
2. Write.js 메시지 전송 후 
- 전송 알림 모달 노출
- 일정 시간 후 메인 페이지로 이동
- 수정 모달 창 스타일 개선
> feat: package.json conflict 해결, write.js 메시지 작성 후 기능 보완

- src/components/Mypage.js
Feat: 읽은 편지 localstorage 저장 기능 구현
읽은 편지는 localstorage에 저장해 새로고침해도 리셋되지 않게 수정(근데 새로고침하면 오류남)
> feat: 읽은 편지 localstorage 저장 기능 구현

- src/App.js
- src/components/Header.js
- src/components/Write.js
1. App.js
- 로컬스토리지 저장된 데이터 초기화 수정
> fix: 데이터 초기화 수정

- src/App.js
- src/components/Header.js
1. localhost 노출 삭제
2. App.js 로컬스토리지 저장 추가
> fix: localhost 삭제, App.js 데이터 로컬스토리지 저장 추가

- src/components/Index2.js
- src/components/Write.js
- src/styles/style.js
feat: 편지 개수에 따라 페이지 이동 제어, style 수정
- Write.js 모달창 수정
- Index2.js 편지 개수에 따라 페이지 이동 제어
- style.js box-shadow props 추가
> feat: 편지 개수에 따라 페이지 이동 제어, style 수정

- src/App.js
- src/components/Header.js
- src/components/Help.js
- src/components/Index.js
- src/components/Letter.js
feat: Letter.js Header.js 수정
-Letter.js 편지 디자인 수정
-Header.js Title 삭제 후 Index.js에 추가
-Index.js 로그인  시 '/mypage'로 이동 기능 구현
> feat: Letter.js Header.js 수정

- src/components/Header.js
fix: Header.js 주석 제거
- Header.js 61~63번째 줄 주석 삭제
> fix: Header.js 주석 제거

- src/components/Footer.js
fix: github 링크 수정
- Footer.js 링크 수정
> fix: github 링크 수정

- src/components/Mypage.js
Feat: 편지 개수 12개로 제한
Mypage.js에서 띄우는 편지의 개수를 최대 12개로 제한하는 기능 추가
> feat: 편지 개수 12개로 제한

- src/components/Letter.js
style: 편지 확인 버튼 스타일 수정
- Letter.js : pc 버전 버튼 호버 스타일 수정
> style: 편지 확인 버튼 스타일 수정

- src/components/Mypage.js
> feat: Mypage.js 링크 공유 버튼 구현

- public/index.html
- src/components/Index2.js
- src/components/Join.js
- src/components/Mypage.js
Fix: 전체 기능 구현 오류 수정
index.html 언어 변경
Mypage.js 황금당근 오류 수정
Index2.js 편지쓰기 버튼 렌더링 조건 수정
Join.js console.log 제거
> fix: 전체 기능 구현 오류 수정

- package.json
- src/App.js
feat: 배포 전 router 관련 설정
package.json homepage 추가
App.js BrowserRouter basename 추가
> feat: 배포 전 router 관련 설정

- src/components/Header.js
- src/components/Help.js
- src/components/Join.js
- src/components/Letter.js
- src/styles/GlobalStyle.js
> fix: 배포 후 수정

- src/App.js
- src/components/Index.js
- src/components/Index2.js
- src/styles/style.js
> fix: router edit

- src/App.js
- src/components/Index2.js
- src/components/Mypage.js
- src/components/Write.js
> fix: 편지쓰기 수정창 오류 수정
